### PR TITLE
Buffer and reassemble chunked transfers with split chunks

### PR DESCRIPTION
**Pull request by shanesveller**
**Help Wanted!**

In one of my attempted uses of Mint, I wanted to make a request to a Kubernetes API to perform a logical "watch" request, which uses Chunked Transfer to send back newline-separated single-line JSON packets to represent events, where each JSON blob arrives as a standard transfer chunk with the hexidecimal length, newline, binary data, newline.

In my practical use, after a little `:sys.trace` investigation, I found that the internal `{:tcp, port, data}` messages that were arriving at my worker process were splitting prior to the entire length of the logical HTTP chunk.

If one of the maintainers has clear direction of how to implement this buffering idea and wants to run with it, I won't be upset, but I'd love to take a crack at it with some guidance if that's an option.

Anyway, I'm fairly confident I'm not providing quite enough information here in this first post, but please let me know of any additional context, examples, etc. that I can provide. I'll also try to update this PR with more proactive content a bit later this morning.

### CODE REVIEW

**Comment by ericmj** [comment]
Applications should not rely on the chunk delimiters in chunked transfer encoding because they may be changed by proxies so it would be unreliable, this works in the same way that you shouldn't rely on TCP packet sizes since it's a stream protocol.

That means your application needs to buffer data until it receives a whole JSON object and newline and do the chunking yourself.

**Comment by shanesveller** [comment]
Sure, no problem! That's useful advice. I'll re-read the docs and do another round of experimentation locally, but I vaguely remember having trouble finding a "one-message-only"/non-recursive equivalent to `Mint.HTTP.stream/2` - perhaps it was my mistake to assume that there would/should be one.

I can just take in and pattern match the raw `:tcp` packets myself, if it comes down to that, but at that point it seems like Mint is only helping me initiate the connection and begin the request and then leaving me to own devices? I'd even have to decode the initial preamble of a chunked request myself, I think? Non-streaming/non-chunked requests appear to be handled much more gracefully than that, so I was hoping to get a similarly positive experience here.

When I _do_ use `Mint.HTTP.stream/2` on the first incoming response `:tcp` message for this style of request, I consistently get a seemingly-spurious `%Mint.HTTPError{module: Mint.HTTP1, reason: :invalid_status_line}, []}` error the first time it recurses, which doesn't sound correct independent of whether I'm approaching Mint with the correct mindset. It didn't point me to the problem of getting an incomplete JSON document, because I wasn't even attempting to decode it yet - just receive the incoming data in the first place.

**Comment by whatyouhide** [comment]
@shanesveller maybe I'm missing something, but it seems like what your application should be doing is something like this:

* get a `:data` response from Mint
* try to parse it as JSON, which will return `{:ok, parsed, rest} | :error | :incomplete`
* if it's a complete document with some `rest` after it, recurse with `rest`, otherwise put `rest` in a buffer
* if it's `:incomplete`, put the whole data in the buffer and wait for the next `:data` response
* when the next `:data` response comes, append it to the buffer and start again

or am I missing something? How is Mint affecting this?

**Comment by ericmj** [comment]
I didn't mean you should decode the chunked transfer encoding yourself. I assumed the Kubernetes API provided some kind of JSON object delimiter on top of the chunked transfer encoding. Can you link me to the documentation of the Kubernetes API and how it uses chunked?

**Comment by shanesveller** [comment]
@ericmj I'm attempting the request below for my test case:

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#watch-list-namespace-v1-core

Conceptually, I'm using code shaped like this, but broken across some `GenStateMachine` functions. I'm trying to distill it down to a useful/shareable public example, but not done with that yet.

```elixir
{:ok, conn} = Mint.HTTP.connect(:http, "localhost", 8001)

{:ok, conn, request_ref} =
  Mint.HTTP.request(
    conn,
    "GET",
    "/api/v1/watch/namespaces?resourceVersion=0&timeoutSeconds=90",
    []
  )

receive do
  {:tcp, _port, _body} = message ->
    Mint.HTTP.stream(conn, message)
  # ...
after
  95_000 -> :done
end
```

I'm not trying to ask anyone to install or otherwise acquire access to Kubernetes just to help me triage what may be user-error, but if you already have access to a cluster, even if it's through Minikube, all you have to do is run `kubectl proxy` and execute that style of request.

@whatyouhide What you've outlined is really similar to the logical flow I'm using successfully with HTTPoison instead, but I'm enthusiastic about trying Mint for this use case and not yet ready to settle on that.

Thank you both for the attention so far!

**Comment by shanesveller** [comment]
This is a public repo that reproduces some of what I'm seeing - I'll try to add more useful information and context to it, but this GenServer trips the error-tuple on `Mint.HTTP.stream/2`:

https://github.com/shanesveller/mint_streaming/blob/777badfd4be8e5213c64f5baef73d90117c81c8c/lib/streamer.ex#L31-L38

All I've done is `mix new --sup`, install Mint from `master`, and then write the linked GenServer module and add it to the Application supervision tree.

**Comment by ericmj** [comment]
I ran the request against k8s and got this responses from the first call to `stream/2`:

```elixir
{:ok,
 %Mint.HTTP1{
   buffer: "",
   host: "localhost",
   private: %{},
   request: %{
     body: {:chunked, nil},
     connection: [],
     content_length: nil,
     headers_buffer: [],
     method: "GET",
     ref: #Reference<0.40772167.3808690177.28596>,
     state: :body,
     status: 200,
     transfer_encoding: ["chunked"],
     version: {1, 1}
   },
   requests: {[], []},
   socket: #Port<0.6>,
   state: :open,
   transport: Mint.Core.Transport.TCP
 },
 [
   {:status, #Reference<0.40772167.3808690177.28596>, 200},
   {:headers, #Reference<0.40772167.3808690177.28596>,
    [
      {"audit-id", "a9391d89-f748-428b-889b-fc871f3681a9"},
      {"content-type", "application/json"},
      {"date", "Thu, 21 Mar 2019 09:59:42 GMT"},
      {"transfer-encoding", "chunked"}
    ]},
   {:data, #Reference<0.40772167.3808690177.28596>,
    "{\"type\":\"ADDED\",\"object\":{\"kind\":\"Namespace\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"kube-system\",\"selfLink\":\"/api/v1/namespaces/kube-system\",\"uid\":\"4c84a6a2-b46a-11e8-9609-42010a96001d\",\"resourceVersion\":\"50\",\"creationTimestamp\":\"2018-09-09T19:55:27Z\",\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"Namespace\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"kube-system\\\",\\\"namespace\\\":\\\"\\\"}}\\n\"}},\"spec\":{\"finalizers\":[\"kubernetes\"]},\"status\":{\"phase\":\"Active\"}}}\n{\"type\":\"ADDED\",\"object\":{\"kind\":\"Namespace\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"default\",\"selfLink\":\"/api/v1/namespaces/default\",\"uid\":\"4c7c187e-b46a-11e8-9609-42010a96001d\",\"resourceVersion\":\"4\",\"creationTimestamp\":\"2018-09-09T19:55:27Z\"},\"spec\":{\"finalizers\":[\"kubernetes\"]},\"status\":{\"phase\":\"Active\"}}}\n{\"type\":\"ADDED\",\"object\":{\"kind\":\"Namespace\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"kube-public\",\"selfLink\":\"/api/v1/namespaces/kube-public\",\"uid\":\"4c8717a8-b46a-11e8-9609-42010a96001d\",\"resourceVersion\":\"9\",\"creationTimestamp\":\"2018-09-09T19:55:27Z\"},\"spec\":{\"finalizers\":[\"kubernetes\"]},\"status\":{\"phase\":\"Active\"}}}\n"}
```

As we can see at the end of the `:data` response the JSON object is delimited by newlines which you can use to get whole JSON objects:

```elixir
{:data, ^ref, string} = ...
[json_object, json_object, ..., buffer_last_part] = :binary.part(string, "\n")
```

Concatenate `buffer_last_part` with the `string` in the next `:data` response.

Also make sure to store the returned `conn` between each `Mint.HTTP.stream/2` call so that you don't get the `:invalid_status_line` error.

**Comment by shanesveller** [comment]
Thank you - this was absolutely repeated user error on my part, starting with not correctly persisting the `conn` from call to call. With @ericmj's suggestion I'm unblocked! 🎉

**Pull request closed without merging**
